backend:
  name: github
  repo: otavio99/blogantilopes
  branch: main    # Branch to update
  base_url: https://decap-cms-auth.vercel.app/
media_folder: 'static'
collections:
  - name: 'mdposts'
    label: 'Posts'
    folder: 'mdposts/'
    slug: "{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Sub Titulo', name: 'subtitle', widget: 'string' }
      - { label: 'authors', name: 'authors', widget: 'string' }
      - { label: 'date', name: 'date', widget: 'datetime', date_format: 'DD/MM/YYYY'}
      - { label: "Body", name: "body", widget: "markdown" }